# -*- coding: utf-8 -*-
"""Netflix Popular Data (2022)  - Basico

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aOH_g3Wrxhx2dEw_AavEag5gT4c5Pv9k

# **1 - Importing Libraries Python**



* **Pandas** - *Software library for data manipulation and analysis. Categorical nominal.*
*   **Numpy** - *Software library for numerical computing in Python. Categorical nominal.*
*   **Matplotlib** - *Software library for creating graphical visualizations in Python. Categorical nominal.*
* **Seaborn** - *Statistical data visualization library for enhancing plots. Categorical nominal.*

## **Machine Learning & Model Training**  

* **LinearRegression** - *Linear regression model for predicting numerical relationships.*  
* **KMeans** - *Clustering algorithm for grouping similar data points.*  
* **DecisionTreeClassifier** - *Supervised learning model for classification tasks.*  

## **Data Preprocessing & Evaluation**  

* **KBinsDiscretizer** - *Transforms continuous variables into discrete categories.*  
* **Mean Squared Error (MSE)** - *Measures average squared differences between actual and predicted values.*  
* **R² Score** - *Evaluates the explanatory power of regression models.*  
* **Classification Report** - *Summarizes precision, recall, and F1-score for classification tasks.*  
* **Train-Test Split** - *Divides dataset into training and testing subsets.*  

---
"""

# Data Manipulation & Visualization
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Machine Learning & Model Training
from sklearn.linear_model import LinearRegression
from sklearn.cluster import KMeans
from sklearn.tree import DecisionTreeClassifier

# Data Preprocessing & Evaluation
from sklearn.preprocessing import KBinsDiscretizer
from sklearn.metrics import mean_squared_error, r2_score, classification_report
from sklearn.model_selection import train_test_split

"""# **2 - Understanding the Data**


*   *he dataset was collected from kaggle: https://www.kaggle.com/datasets/narayan63/netflix-popular-movies-dataset?resource=download*




"""

n_movies = '/content/n_movies.csv'
df = pd.read_csv(n_movies)
df.head()

"""**Data Dictionary**

**1.   Title:** Title of the movie or series. Categorical nominal.

**2.   Year:** Year of release or airing period (e.g., "(2022)", "(2018–)"). Categorical ordinal.

**3.   Certificate:** Content rating (e.g., TV-MA, TV-14). Categorical nominal.

**4.   Duration:** Duration of the movie or episode (e.g., "30 min", "356 min"). Categorical ordinal.

**5.   Genre:** Genre(s) of the movie or series (e.g., "Action, Comedy, Drama"). Categorical nominal.

**6.   Rating:** Average rating (e.g., 8.5, 5.9). Numerical continuous.
description: Summary or synopsis of the content. Categorical nominal.

**7.   Stars:** List of lead actors. Categorical nominal.

**8.   Votes:** Number of votes received. Numerical discrete (stored as text due to separators, e.g., "177,031").

Looking at dataset general information.








"""

df.info()

print(f'The dataset has {df.shape[0]} rows and {df.shape[1]} columns.')

df.describe(include='all')

"""Some insights:

1.   The average rating is approximately 6.8, indicating that most movies/
     series have good audience feedback.

2.   The median duration of movies/episodes is 67 minutes, suggesting a typical
     short-form or standard runtime.

3.   The top 3 most common genres are: Comedy, Drama, and Animation. Therefore,
     the most watched genre was Comedy.

4.   On average, movies/series received around 19,523 votes.
     
5.   The number of  votes ranges from 5 to 1,844,075.

6.   The ratings are not skewed, as the mean rating is close to the median.

7.   Many columns contain NaN values, preventing their display.

8.   The most-watched series on Netflix, as shown in the table, was "Top Gear"

9.   The data types for the columns year, duration, stars, and votes are incorrect and need to be adjusted.

# **3 - Data Cleaning**

 *Data cleaning was performed by removing missing values, eliminating duplicates, selecting relevant columns, and sorting the DataFrame by rating in descending order.*


- *Data that had NaN values has been removed.*
- *Data types have been corrected.*
- *Removed the columns: certificate, genre, and stars.*

**I will correct some technical issues related to the data types that are incorrect in the following fields: year (str), duration (str), and votes (str). These fields will be transformed to the appropriate types, float64 or int.**
"""

df['year'] = df['year'].astype(str).str.extract(r'(\d{4})')
df['year'] = pd.to_numeric(df['year'], errors='coerce').fillna(0).astype(int)
df['duration'] =  df['duration'].astype(str).str.extract(r'(\d+)')
df['duration'] = pd.to_numeric(df['duration'], errors='coerce').fillna(0).astype(int)
df['votes'] = df['votes'].astype(str).str.extract(r'(\d+)')
df['votes'] = pd.to_numeric(df['votes'], errors='coerce').fillna(0).astype(int)
print(df)

df = df[['title', 'year', 'duration', 'genre', 'rating', 'description', 'votes']]

df.head()

df.dropna(inplace=True)
df.duplicated().sum()

df.sort_values(by='rating' ,ascending=False)

"""**After cleaning up some data that was hindering the analysis in the table, we can now focus on the important points we really want to analyze.**

**Some insights:**

1. *All missing values were removed, ensuring the analysis is done with complete data.*

2. *Duplicates were checked, and there are no duplicate entries in the dataset, maintaining data integrity.*

3. *Only the columns title, year, duartion, genre, rating, description, and votes were retained, focusing on the most relevant information for the analysis.*

4. *The DataFrame was sorted by the rating column in descending order, highlighting the titles with the best ratings.*

5. *After cleaning, the data is better organized, facilitating the extraction of valuable insights.*

6. *Cleaning the data allows us to focus on the important points, eliminating noise and inconsistencies.*

7. *With sorted and clean data, visualization and analysis become more efficient and accurate.*

8. *The subsequent analysis will be based on reliable data, providing more precise and meaningful insights.*

9. *These titles represent the crème de la crème of Netflix's offerings, with "BoJack Horseman" being the standout favorite.*

10. *The most popular genres are Comedy, Drama, and Animation, suggesting that these genres are highly favored by Netflix viewers.*

11. *Titles with higher votes tend to have higher ratings, showing a positive correlation between audience engagement and quality perception.*

12. *Most titles have ratings between 5 and 8, indicating that the majority of popular Netflix content is well-received by audiences.*

"""

df.info()

"""**After refining the data and correcting the null values, we will be able to use the data effectively for our analysis.**"""

df = df[['title', 'year', 'duration', 'rating', 'votes']]
df.describe()

"""# **4 - Data Analysis**
*In this section, we conduct an in-depth analysis of the Netflix Popular Data (2022) dataset to uncover meaningful insights. The goal is to explore trends in ratings, duration, and audience engagement while identifying potential correlations between variables.*
"""

plt.figure(figsize=(20, 6))
sns.scatterplot(data=df, x='year', y='duration', hue='rating', palette='rocket')
plt.title('Classification of Movies/Series by Year and Duration')
plt.xlabel('Year')
plt.ylabel('Duration')
plt.show()

"""**Some Insights:**

1. *Until the 1980s, Netflix films and series were produced with short durations, up to 200 minutes, to capture the audience's attention.*

2. *Starting in the 1990s, there was a significant increase in the number of short-duration films and series, reflecting a change in audience preferences.*

3. *In the 2000s, the number of series and films with durations of up to 200 minutes gradually increased, along with the rise in productions.*

4. *Around 2020, Netflix began importing more series and films with durations exceeding 200 minutes to cater to the demand for longer and more engaging content.*
"""

plt.figure(figsize=(12, 6))
sns.scatterplot(data=df, x='duration', y='rating')
plt.title('Relationship between Duration and Rating')
plt.xlabel('Duration (minutes)')
plt.ylabel('Rating')
plt.show()

"""**Some Insights:**

1.*Shorter Productions (Under 60 min): Tend to have a wider spread in ratings. Some achieve high acclaim, while others receive lower scores, possibly due to varied audience expectations.*

2.*Standard-Length Productions (60-120 min): This range seems to concentrate around higher ratings, indicating that most well-received content falls within this typical movie or episode length.*

3.*Extended Duration (Over 120 min): Shows a mix of ratings, but longer films and episodes often receive either very high or low reviews—suggesting that extended storytelling can be polarizing.*

4.*Outliers: A few productions with extremely long durations tend to receive mixed feedback, potentially reflecting niche appeal or pacing challenges.*
"""

plt.figure(figsize=(12, 6))
sns.histplot(data=df, x='year', bins=30, kde=True, color='royalblue')
plt.title('Temporal Distribution of Netflix Movies and Series')
plt.xlabel('Year')
plt.ylabel('Count')
plt.show()

"""**Some Insights:**

1.*Early Years (Pre-2000s): The number of productions was relatively low. Netflix wasn't yet a dominant force in streaming, and content creation was more limited.*

2.*Boom in the 2000s: The volume of movies and series started increasing significantly, probably driven by the expansion of digital platforms and streaming services.*

3.*2010s Growth: Netflix firmly established itself as a major player in entertainment, leading to an explosion of new content each year.*

4.*Recent Trends (2020s): There's a clear rise in longer-duration productions, suggesting a shift towards more immersive storytelling that keeps audiences engaged for extended periods.*
"""

plt.figure(figsize=(12, 6))
sns.boxplot(data=df, x='category', y='rating', hue='category', palette='coolwarm', legend=False)
plt.title('Boxplot of Ratings Across Duration Categories')
plt.xlabel('Duration Category')
plt.ylabel('Rating')
plt.xticks(rotation=45, ha='right')
plt.show()

"""**Some Insights:**

1. *Short Productions (Under 100 min) – Ratings are all over the place! Some short films and series are highly praised, while others get lower scores. This makes sense—shorter content varies a lot, from quick documentaries to indie projects, meaning audience expectations can differ.*

2. *Medium-Length (100-200 min) – This range consistently gets solid ratings. It seems like most people enjoy content that fits within a standard movie or episode length. Not too short, not too long—just the right balance for engaging storytelling.*

3. *Long Productions (200-300 min) – Ratings start to get a little more unpredictable. Some longer films and episodes receive high praise, but others struggle. It's likely that pacing and storytelling play a big role—if done well, longer content keeps audiences hooked, but if not, it can lose momentum.*

4. *Very Long (Over 300 min) – This category is the most extreme. Either the content is loved or heavily criticized. That makes sense—watching something this long requires strong narrative depth to keep people engaged. It's probably why some of these productions become cult classics, while others feel excessive.*

# **5- Conclusion**

**This project was my first data analysis focused on data science, examining movies and series from** **Netflix (Unofficial)**. **Throughout the study, I identified some interesting patterns. Here are the most relevant findings:**

### **1. Increase in Content Production Over Time**
- *Until the 2000s, Netflix had a relatively small number of productions.*
- *With the rise of streaming services, there was a significant expansion in content creation.*

### **2. Impact of Duration on Ratings**
- *Films and series with a **medium duration (100-200 min)** tend to receive **more stable and positive ratings**.
- *Short and long productions show **more unpredictable ratings**, suggesting audiences prefer a **balanced length for storytelling**.*

### **3. Trends After 2020**
- *In recent years, there has been **an increase in productions exceeding 200 minutes**.
- *This might reflect a growing interest in **longer and more detailed narratives**.*

### **4. Correlation Between Votes and Ratings**
- *The analysis suggests that movies and series with **higher vote counts** tend to have **better ratings**.
- *This could indicate that **popular titles attract viewers who already enjoy that genre or style**.*


**This project provided valuable insights into Netflix's content production and audience reception. There's still plenty of room to refine the analysis and extract deeper insights from the data.**
"""
